[package]
name = "."
version = "0.1.0"
description = "NNS - The Nockchain Name Service"

[dependencies.nockchain-hoon]
git = "https://github.com/nocktoshi/nockchain.git"
commit = "f1c7cd87883bd7883d06a898361884d1cb18f98e"
path = "hoon"

[dependencies.vesl-lib]
git = "https://github.com/nocktoshi/vesl-core.git"
commit = "556f707db7f896a032fba4fee87387f8e6e101d7"
path = "protocol/lib"
files = [
  "vesl-graft",
  "vesl-merkle",
  "vesl-prover",
  "vesl-stark-verifier",
  "vesl-verifier",
]
