[package]
name = "."
version = "0.1.0"
description = "NNS - The Nockchain Name Service"

[dependencies.nockchain-hoon]
git = "https://github.com/nocktoshi/nockchain.git"
commit = "ea5f831635f32acdd55e9ea60890e012dcd1b13f"
path = "hoon"

[dependencies.vesl-lib]
git = "https://github.com/nocktoshi/vesl-core.git"
commit = "dc9382cd2110cb39561bf4abdc47d7d7f88029b5"
path = "protocol/lib"
files = [
  "vesl-graft",
  "vesl-merkle",
  "vesl-prover",
  "vesl-stark-verifier",
  "vesl-verifier",
]
